# set environment variable AWS_CLIENT_TIMEOUT to increase timeout

service: open-bot-v1

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 256
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"

plugins:
  - serverless-offline

package:
  individually: true
  exclude:
    - '**'
  include:
    - handlers.js

functions:
  processIssue:
    handler: handlers.processIssue
    package:
      include:
        - lib/open-bot-process-issue/**
        - lib/open-bot/**
        - config.json
    events:
      - sns: processIssue
  handleGithubEvent:
    handler: handlers.handleGithubEvent
    package:
      include:
        - lib/open-bot-handle-github-event/**
        - lib/open-bot/**
        - config.json
    events:
      - http:
          path: github
          method: POST
          timeout: 20


